import 'package:flutter/widgets.dart';

/// Add new languages by extending [supportedLanguages] and [dictionary].
class AppLocalizations {
  AppLocalizations._();

  static const List<String> supportedLanguages = ['en', 'ru', 'tr'];

  static const Map<String, Map<String, String>> dictionary = {
    'en': {
      'appTitle': 'VPS Capture',
      'captureSetupSectionTitle': 'Capture setup',
      'captureSetupSectionHint': 'Select how the signal is captured, which devices are used, and which codec encodes the recording.',
      'captureSourceHelp': 'Changes the connection type used for device scanning and recording.',
      'captureSourceLabel': 'Source type',
      'videoDeviceHelp': 'Chooses the video signal source that will be recorded.',
      'audioDeviceHelp': 'Chooses the audio input paired with the recording.',
      'codecHelp': 'Defines which encoder ffmpeg uses for the final video.',
      'codecLabel': 'Recording codec',
      'sourceTypeAvFoundation': 'macOS camera/screen (AVFoundation)',
      'sourceTypeDirectShow': 'Windows capture device (DirectShow)',
      'sourceTypeDeckLink': 'Blackmagic DeckLink',
      'setupTitle': 'VPS Capture • Settings',
      'workTitle': 'VPS Capture • Work',
      'currentThread': 'CURRENT THREAD',
      'nextThread': 'NEXT THREAD',
      'postponedParticipants': 'POSTPONED',
      'endThread': 'END',
      'clearPostponed': 'CLEAR',
      'installAutomatically': 'Install ffmpeg automatically',
      'installAutomaticallyQuestionTitle': 'Download the latest ffmpeg?',
      'installAutomaticallyQuestionMessage': 'Do you really want to download the latest ffmpeg version now?',
      'pickFfmpeg': 'Pick ffmpeg path...',
      'pickFfplay': 'Pick ffplay path...',
      'startPreview': 'Start Preview',
      'stopPreview': 'Stop Preview',
      'startTestRecording': 'Start Test Recording',
      'stopTestRecording': 'Stop Test Recording',
      'notSelected': 'not selected',
      'outputFolder': 'Output folder',
      'chooseOutputFolder': 'Choose output folder',
      'captureSource': 'Capture source type',
      'scanDevices': 'Scan devices',
      'codec': 'Codec',
      'bufferMin': 'Buffer min',
      'preRollSec': 'Pre-roll sec',
      'recordingStartTrimSec': 'Trim start, sec',
      'detectedVideoDevices': 'Video devices',
      'detectedAudioDevices': 'Audio devices',
      'selectedVideoDevices': 'Choose video device',
      'selectedAudioDevices': 'Choose audio device',
      'continueToWork': 'Continue to Work Screen',
      'loadSchedule': 'Load schedule',
      'scheduleEditorLabel': 'Schedule input',
      'scheduleEditorHint': 'One line: FIO;CITY;APPARATUS (optional)',
      'applySchedule': 'Apply schedule',
      'backToSetup': 'Back to setup',
      'startHotkey': 'START (Space)',
      'stopHotkey': 'STOP (Space)',
      'postponeHotkey': 'POSTPONE (Ctr+Left Alt)',
      'startStopButtonStart': 'START',
      'startStopButtonStop': 'STOP',
      'restoreEntry': 'Restore',
      'postponeEntry': 'Postpone',
      'deleteEntry': 'Delete',
      'addParticipant': 'Add participant',
      'participantNameLabel': 'Name',
      'participantCityLabel': 'City',
      'participantApparatusLabel': 'Apparatus (optional)',
      'add': 'Add',
      'cancel': 'Cancel',
      'pending': 'PENDING',
      'active': 'ACTIVE',
      'done': 'DONE',
      'postponed': 'POSTPONED',
      'language': 'Language',
      'allThreads': 'All streams',
      'allTypes': 'All routines',
      'resetFilters': 'Reset filters',
      'displayedCounter': 'Displayed ',
      'nameGifsTitre': 'GIF-titles',
      'labelTimerGifs': 'Timer GIFs (sec)',
      'hintTimerGifs': 'Enter a number',
      'suffixTimerGifs': 'sec',
      'setupVersion': 'version',
      'fullResetSettings': 'Full reset settings',
      'fullResetWarningTitle': 'Reset all settings?',
      'fullResetWarningMessage': 'This will return all settings to defaults, clear the schedule queue and delete saved temporary data. This action cannot be undone.',
      'reset': 'Reset',
      'ffmpegErrorTitle': 'Recording could not start',
      'ffmpegErrorMessage': 'ffmpeg reported an error when recording started. You can copy or save the full report for the developer.',
      'copyError': 'Copy report',
      'saveError': 'Save report',
      'close': 'Close',
      'ffmpegErrorCopied': 'ffmpeg error report copied to clipboard',
      'ffmpegErrorSaved': 'ffmpeg error report saved',
      "pasteFromClipboard": "Paste from the buffer",
      "loadFromFile": "Upload from a file",
      "pasteScheduleData": "Insert the start list",
      "scheduleData": "The starting list",
      "pasteScheduleHint": "Insert the start list here...",
      "clipboardEmpty": "The clipboard is empty",
      "emptyScheduleData": "The start list is empty",
      "load": "Load",
      "labelDropDownThread": "Thread",
      "labelDropDownRoutines": "Routin",
      "labelDropDownTitres": "Titer",
      'gifTitleSettingsTitle': 'Title settings',
      'gifTitleSettingsHint': 'Adjust text size, colors, and X/Y coordinates for each GIF template. Changes are applied immediately and can be checked with a test title.',
      'gifTitleTemplateLabel': 'GIF template',
      'gifTitleOpenSettings': 'Title settings',
      'gifTitleRunTest': 'Run test title',
      'gifTitleResetCurrent': 'Reset current GIF',
      'gifTitleNameSection': 'Name line',
      'gifTitleCitySection': 'City line',
      'gifTitleTextSize': 'Text size',
      'gifTitleTextColor': 'Text color',
      'gifTitleHorizontalPosition': 'X position',
      'gifTitleVerticalPosition': 'Y position',
      'gifTitleColorInvalid': 'Enter a color in #RRGGBB or #AARRGGBB format',
      "labelDropDownThreadList": "THREAD",
      'judgeWebPanelTitle': 'Judge replay page',
      'judgeWebPanelDescription': 'Judges can open this page from another device on the same network to see completed routines and watch replays.',
      'judgeWebPort': 'Judge HTTP port',
      'judgeWebServerRunning': 'Judge page is online',
      'judgeWebServerStopped': 'Judge page is offline',
      'judgeWebServerSetupStopped': 'Judge page is stopped in settings',
      'judgeWebStatusDetails': 'Details',
      'judgeWebStatusDialogTitle': 'Judge page addresses',
      'judgeWebStatusDialogEmpty': 'The server is not active right now.',
      'judgeWebCopyAddress': 'Copy address',
      'judgeWebAddressCopied': 'Address copied to clipboard',
      'judgeWebOpenHint': 'Open in any browser on the same network:',
      'judgeWebServerError': 'Judge page error',
      'judgePageTitle': 'Judge replay panel',
      'judgeAutoRefreshHint': 'Updates automatically. Keep the page open during the competition.',
      'judgeSearchPlaceholder': 'Search by athlete, city, or apparatus',
      'judgeStatusDoneOnly': 'Performed',
      'judgeStatusActiveOnly': 'On floor now',
      'judgeStatusAll': 'All athletes',
      'judgeStatusPendingOnly': 'Waiting',
      'judgeStatusPostponedOnly': 'Postponed',
      'judgeThreadAll': 'All threads',
      'judgeStatDone': 'Performed',
      'judgeStatActive': 'Active',
      'judgeStatPending': 'Waiting',
      'judgeStatReplays': 'With replay',
      'judgeEmpty': 'No athletes match the selected filters yet.',
      'judgeOpenReplay': 'Open replay',
      'judgeReplayMissing': 'Replay will appear here after export',
      'judgeStartedAt': 'Started',
      'judgeLastUpdate': 'Last update'
    },
    'ru': {
      'appTitle': 'ВПС Захват',
      'captureSetupSectionTitle': 'Параметры захвата',
      'captureSetupSectionHint': 'Здесь выбирается тип подключения, активные устройства и кодек, которым будет кодироваться запись.',
      'captureSourceHelp': 'Меняет способ подключения источника и то, как программа ищет устройства для записи.',
      'captureSourceLabel': 'Тип подключения',
      'videoDeviceHelp': 'Определяет, с какого видеовхода брать картинку для записи.',
      'audioDeviceHelp': 'Определяет, какой аудиовход будет записываться вместе с видео.',
      'codecHelp': 'Определяет, каким кодеком ffmpeg будет сжимать итоговый файл.',
      'codecLabel': 'Кодек записи',
      'sourceTypeAvFoundation': 'Камера/экран macOS (AVFoundation)',
      'sourceTypeDirectShow': 'Устройство захвата Windows (DirectShow)',
      'sourceTypeDeckLink': 'Blackmagic DeckLink',
      'setupTitle': 'ВПС Захват • Настройки',
      'workTitle': 'ВПС Захват • Работа',
      'currentThread': 'ТЕКУЩИЙ ПОТОК',
      'nextThread': 'СЛЕДУЮЩИЙ ПОТОК',
      'postponedParticipants': 'ОТЛОЖЕННЫЕ',
      'endThread': 'КОНЕЦ',
      'clearPostponed': 'ОЧИСТИТЬ',
      'installAutomatically': 'Установить автоматически ffmpeg',
      'installAutomaticallyQuestionTitle': 'Скачать последнюю версию ffmpeg?',
      'installAutomaticallyQuestionMessage': 'Точно ли хотите скачать последнюю версию ffmpeg?',
      'pickFfmpeg': 'Выбрать путь к ffmpeg...',
      'pickFfplay': 'Выбрать путь к ffplay...',
      'startPreview': 'Запустить превью',
      'stopPreview': 'Остановить превью',
      'startTestRecording': 'Запустить тестовую запись',
      'stopTestRecording': 'Остановить тестовую запись',
      'notSelected': 'не выбрано',
      'outputFolder': 'Папка вывода',
      'chooseOutputFolder': 'Выбрать папку вывода',
      'captureSource': 'Тип источника захвата',
      'scanDevices': 'Сканировать устройства',
      'codec': 'Кодек',
      'bufferMin': 'Буфер, мин',
      'preRollSec': 'Преролл, сек',
      'recordingStartTrimSec': 'Срезать начало, сек',
      'detectedVideoDevices': 'Видеоустройства',
      'detectedAudioDevices': 'Аудиоустройства',
      'selectedVideoDevices': 'Выберите видеоустройство',
      'selectedAudioDevices': 'Выберите аудиоустройство',
      'continueToWork': 'Перейти к рабочему экрану',
      'loadSchedule': 'Загрузить расписание',
      'scheduleEditorLabel': 'Ввод расписания',
      'scheduleEditorHint': 'Одна строка: ФИО;ГОРОД;СНАРЯД (необязательно)',
      'applySchedule': 'Применить расписание',
      'backToSetup': 'Назад к настройке',
      'startHotkey': 'СТАРТ (Пробел)',
      'stopHotkey': 'СТОП (Пробел)',
      'postponeHotkey': 'ОТЛОЖИТЬ (Ctr+Левый Alt)',
      'startStopButtonStart': 'СТАРТ',
      'startStopButtonStop': 'СТОП',
      'restoreEntry': 'Вернуть',
      'postponeEntry': 'Отложить',
      'deleteEntry': 'Удалить',
      'addParticipant': 'Добавить участницу',
      'participantNameLabel': 'ФИО',
      'participantCityLabel': 'Город',
      'participantApparatusLabel': 'Снаряд (необязательно)',
      'add': 'Добавить',
      'cancel': 'Отмена',
      'pending': 'В ОЧЕРЕДИ',
      'active': 'АКТИВНО',
      'done': 'ГОТОВО',
      'postponed': 'ОТЛОЖЕНО',
      'language': 'Язык',
      'allThreads': 'Все потоки',
      'allTypes': 'Все виды',
      'resetFilters': 'Сбросить фильтры',
      'displayedCounter': 'Отображено ',
      'nameGifsTitre': 'GIF-титры',
      'labelTimerGifs': 'GIF-таймер (сек)',
      'hintTimerGifs': 'Введите число',
      'suffixTimerGifs': 'сек',
      'setupVersion': 'версия',
      'fullResetSettings': 'Полный сброс настроек',
      'fullResetWarningTitle': 'Сбросить все настройки?',
      'fullResetWarningMessage': 'Все настройки вернутся к значениям по умолчанию, очередь расписания и временные данные будут удалены. Это действие нельзя отменить.',
      'reset': 'Сбросить',
      'ffmpegErrorTitle': 'Не удалось начать запись',
      'ffmpegErrorMessage': 'Во время старта записи ffmpeg вернул ошибку. Полный отчет можно скопировать или сохранить и отправить разработчику.',
      'copyError': 'Скопировать отчет',
      'saveError': 'Сохранить отчет',
      'close': 'Закрыть',
      'ffmpegErrorCopied': 'Отчет об ошибке ffmpeg скопирован',
      'ffmpegErrorSaved': 'Отчет об ошибке ffmpeg сохранен',
      "pasteFromClipboard": "Вставить из буфера",
      "loadFromFile": "Загрузить из файла",
      "pasteScheduleData": "Вставить стартовый список",
      "scheduleData": "Стартовый список",
      "pasteScheduleHint": "Вставьте сюда стартовый список...",
      "clipboardEmpty": "Буфер обмена пуст",
      "emptyScheduleData": "Стартовый список пуст",
      "load": "Загрузить",
      "labelDropDownThread": "Поток",
      "labelDropDownRoutines": "Вид",
      "labelDropDownTitres": "Титр",
      'gifTitleSettingsTitle': 'Настройки титров',
      'gifTitleSettingsHint': 'Изменяйте размер текста, цвета и координаты X/Y для каждого GIF-шаблона. Изменения применяются сразу, а результат можно проверить тестовым титром.',
      'gifTitleTemplateLabel': 'GIF-шаблон',
      'gifTitleOpenSettings': 'Настройки титров',
      'gifTitleRunTest': 'Запустить тестовый титр',
      'gifTitleResetCurrent': 'Сбросить текущий GIF',
      'gifTitleNameSection': 'Строка ФИО',
      'gifTitleCitySection': 'Строка города',
      'gifTitleTextSize': 'Размер текста',
      'gifTitleTextColor': 'Цвет текста',
      'gifTitleHorizontalPosition': 'Координата X',
      'gifTitleVerticalPosition': 'Координата Y',
      'gifTitleColorInvalid': 'Введите цвет в формате #RRGGBB или #AARRGGBB',
      "labelDropDownThreadList": "ПОТОК",
      'judgeWebPanelTitle': 'Страница повторов для судей',
      'judgeWebPanelDescription': 'Судьи смогут открыть эту страницу с любого устройства в локальной сети и сразу видеть уже выступивших участников и их повторы.',
      'judgeWebPort': 'HTTP-порт для судей',
      'judgeWebServerRunning': 'Страница судей запущена',
      'judgeWebServerStopped': 'Страница судей остановлена',
      'judgeWebServerSetupStopped': 'Страница судей остановлена в настройках',
      'judgeWebStatusDetails': 'Подробнее',
      'judgeWebStatusDialogTitle': 'Адреса страницы судей',
      'judgeWebStatusDialogEmpty': 'Сервер сейчас не запущен.',
      'judgeWebCopyAddress': 'Скопировать адрес',
      'judgeWebAddressCopied': 'Адрес скопирован в буфер обмена',
      'judgeWebOpenHint': 'Откройте в браузере в этой же сети:',
      'judgeWebServerError': 'Ошибка страницы судей',
      'judgePageTitle': 'Панель повторов для судей',
      'judgeAutoRefreshHint': 'Обновляется автоматически. Страницу можно держать открытой весь старт.',
      'judgeSearchPlaceholder': 'Поиск по участнику, городу или виду',
      'judgeStatusDoneOnly': 'Уже выступили',
      'judgeStatusActiveOnly': 'Выступает сейчас',
      'judgeStatusAll': 'Все участники',
      'judgeStatusPendingOnly': 'Ожидают',
      'judgeStatusPostponedOnly': 'Отложены',
      'judgeThreadAll': 'Все потоки',
      'judgeStatDone': 'Выступили',
      'judgeStatActive': 'Активно',
      'judgeStatPending': 'Ожидают',
      'judgeStatReplays': 'Есть повторы',
      'judgeEmpty': 'По текущим фильтрам участников пока нет.',
      'judgeOpenReplay': 'Открыть повтор',
      'judgeReplayMissing': 'Повтор появится после сохранения клипа',
      'judgeStartedAt': 'Старт',
      'judgeLastUpdate': 'Последнее обновление'
    },
    'tr': {
      'appTitle': 'VPS Capture',
      'captureSetupSectionTitle': 'Yakalama ayarları',
      'captureSetupSectionHint': 'Burada bağlantı türünü, kullanılacak cihazları ve kaydı kodlayacak kodeği seçersiniz.',
      'captureSourceHelp': 'Cihaz taraması ve kayıt için kullanılan bağlantı türünü değiştirir.',
      'captureSourceLabel': 'Kaynak türü',
      'videoDeviceHelp': 'Kaydedilecek görüntü girişini seçer.',
      'audioDeviceHelp': 'Video ile birlikte kaydedilecek ses girişini seçer.',
      'codecHelp': 'Son videonun ffmpeg tarafından hangi kodekle kodlanacağını belirler.',
      'codecLabel': 'Kayıt kodeği',
      'sourceTypeAvFoundation': 'macOS kamera/ekranı (AVFoundation)',
      'sourceTypeDirectShow': 'Windows yakalama aygıtı (DirectShow)',
      'sourceTypeDeckLink': 'Blackmagic DeckLink',
      'setupTitle': 'VPS Capture • Ayarlar',
      'workTitle': 'VPS Capture • Çalışma',
      'currentThread': 'MEVCUT AKIŞ',
      'nextThread': 'SONRAKİ AKIŞ',
      'postponedParticipants': 'ertelenmiş',
      'endThread': 'BİTİŞ',
      'clearPostponed': 'açık',
      'installAutomatically': 'ffmpeg otomatik kur',
      'installAutomaticallyQuestionTitle': 'En güncel ffmpeg indirilsin mi?',
      'installAutomaticallyQuestionMessage': 'En güncel ffmpeg sürümünü şimdi indirmek istediğinizden emin misiniz?',
      'pickFfmpeg': 'ffmpeg yolunu seç...',
      'pickFfplay': 'ffplay yolunu seç...',
      'startPreview': 'Önizlemeyi başlat',
      'stopPreview': 'Önizlemeyi durdur',
      'startTestRecording': 'Test kaydını çalıştır',
      'stopTestRecording': 'Test kaydını durdur',
      'notSelected': 'seçilmedi',
      'outputFolder': 'Çıktı klasörü',
      'chooseOutputFolder': 'Çıktı klasörü seç',
      'captureSource': 'Yakalama kaynağı türü',
      'scanDevices': 'Cihazları tara',
      'codec': 'Kodek',
      'bufferMin': 'Arabellek dk',
      'preRollSec': 'Ön kayıt sn',
      'recordingStartTrimSec': 'Başlangıcı kes, sn',
      'detectedVideoDevices': 'Video cihazları',
      'detectedAudioDevices': 'Ses cihazları',
      'selectedVideoDevices': 'Bir video cihazı seçin',
      'selectedAudioDevices': 'Bir ses cihazı seçin',
      'continueToWork': 'Çalışma ekranına geç',
      'loadSchedule': 'Program yükle',
      'scheduleEditorLabel': 'Program girişi',
      'scheduleEditorHint': 'Her satır: AD SOYAD;ŞEHİR;EKİPMAN (opsiyonel)',
      'applySchedule': 'Programı uygula',
      'backToSetup': 'Kuruluma dön',
      'startHotkey': 'BAŞLAT (Space)',
      'stopHotkey': 'DURDUR (Space)',
      'postponeHotkey': 'ERTELE (Ctr+Sol Alt)',
      'startStopButtonStart': 'BAŞLAT',
      'startStopButtonStop': 'DURDUR',
      'restoreEntry': 'Geri yükle',
      'postponeEntry': 'Ertele',
      'deleteEntry': 'Sil',
      'addParticipant': 'Katılımcı ekle',
      'participantNameLabel': 'Ad Soyad',
      'participantCityLabel': 'Şehir',
      'participantApparatusLabel': 'Ekipman (opsiyonel)',
      'add': 'Ekle',
      'cancel': 'İptal',
      'pending': 'BEKLİYOR',
      'active': 'AKTİF',
      'done': 'TAMAM',
      'postponed': 'ERTELENDİ',
      'language': 'Dil',
      'allThreads': 'Tüm konular',
      'allTypes': 'Her türlü',
      'resetFilters': 'Filtreleri sıfırla',
      'displayedCounter': 'Görüntülenen ',
      'nameGifsTitre': 'GIF Kredileri',
      'labelTimerGifs': 'GIF zamanlayıcısı (sn)',
      'hintTimerGifs': 'Numarayı girin',
      'suffixTimerGifs': 'sn',
      'setupVersion': 'versiyon',
      'fullResetSettings': 'Ayarları tamamen sıfırla',
      'fullResetWarningTitle': 'Tüm ayarlar sıfırlansın mı?',
      'fullResetWarningMessage': 'Bu işlem tüm ayarları varsayılana döndürür, program kuyruğunu temizler ve geçici verileri siler. Bu işlem geri alınamaz.',
      'reset': 'Sıfırla',
      'ffmpegErrorTitle': 'Kayıt başlatılamadı',
      'ffmpegErrorMessage': 'Kayıt başlatılırken ffmpeg hata bildirdi. Geliştiriciye göndermek için tam raporu kopyalayabilir veya kaydedebilirsiniz.',
      'copyError': 'Raporu kopyala',
      'saveError': 'Raporu kaydet',
      'close': 'Kapat',
      'ffmpegErrorCopied': 'ffmpeg hata raporu panoya kopyalandı',
      'ffmpegErrorSaved': 'ffmpeg hata raporu kaydedildi',
      "pasteFromClipboard": "Arabellekten yapıştır",
      "loadFromFile": "Bir dosyadan yükleme",
      "pasteScheduleData": "Başlangıç listesini ekle",
      "scheduleData": "Başlangıç listesi",
      "pasteScheduleHint": "Başlangıç listesini buraya ekleyin...",
      "clipboardEmpty": "Pano boş",
      "emptyScheduleData": "Başlangıç listesi boş",
      "load": "Yüklemek",
      "labelDropDownThread": "Konu",
      "labelDropDownRoutines": "Rutin",
      "labelDropDownTitres": "Titre",
      'gifTitleSettingsTitle': 'Jenerik ayarları',
      'gifTitleSettingsHint': 'Her GIF şablonu için metin boyutunu, renkleri ve X/Y koordinatlarını ayarlayın. Değişiklikler hemen uygulanır ve test jeneriği ile kontrol edilebilir.',
      'gifTitleTemplateLabel': 'GIF şablonu',
      'gifTitleOpenSettings': 'Jenerik ayarları',
      'gifTitleRunTest': 'Test jeneriğini çalıştır',
      'gifTitleResetCurrent': 'Geçerli GIF sıfırla',
      'gifTitleNameSection': 'İsim satırı',
      'gifTitleCitySection': 'Şehir satırı',
      'gifTitleTextSize': 'Metin boyutu',
      'gifTitleTextColor': 'Metin rengi',
      'gifTitleHorizontalPosition': 'X konumu',
      'gifTitleVerticalPosition': 'Y konumu',
      'gifTitleColorInvalid': '#RRGGBB veya #AARRGGBB biçiminde bir renk girin',
      "labelDropDownThreadList": "KONU",
      'judgeWebPanelTitle': 'Hakem tekrar sayfası',
      'judgeWebPanelDescription': 'Hakemler aynı ağdaki başka bir cihazdan bu sayfayı açıp tamamlanan sporcuları ve tekrarlarını görebilir.',
      'judgeWebPort': 'Hakem HTTP portu',
      'judgeWebServerRunning': 'Hakem sayfası çalışıyor',
      'judgeWebServerStopped': 'Hakem sayfası kapalı',
      'judgeWebServerSetupStopped': 'Hakem sayfası ayarlarda durdurulur',
      'judgeWebStatusDetails': 'Detaylar',
      'judgeWebStatusDialogTitle': 'Hakem sayfası adresleri',
      'judgeWebStatusDialogEmpty': 'Sunucu şu anda aktif değil.',
      'judgeWebCopyAddress': 'Adresi kopyala',
      'judgeWebAddressCopied': 'Adres panoya kopyalandı',
      'judgeWebOpenHint': 'Aynı ağdaki tarayıcıda açın:',
      'judgeWebServerError': 'Hakem sayfası hatası',
      'judgePageTitle': 'Hakem tekrar paneli',
      'judgeAutoRefreshHint': 'Otomatik güncellenir. Yarışma boyunca sayfayı açık bırakabilirsiniz.',
      'judgeSearchPlaceholder': 'Sporcu, şehir veya alete göre ara',
      'judgeStatusDoneOnly': 'Tamamlananlar',
      'judgeStatusActiveOnly': 'Şu anda sahnede',
      'judgeStatusAll': 'Tüm sporcular',
      'judgeStatusPendingOnly': 'Bekleyenler',
      'judgeStatusPostponedOnly': 'Ertelenenler',
      'judgeThreadAll': 'Tüm akışlar',
      'judgeStatDone': 'Tamamlandı',
      'judgeStatActive': 'Aktif',
      'judgeStatPending': 'Bekliyor',
      'judgeStatReplays': 'Tekrar var',
      'judgeEmpty': 'Seçilen filtreler için henüz sporcu yok.',
      'judgeOpenReplay': 'Tekrarı aç',
      'judgeReplayMissing': 'Klip kaydedilince burada görünecek',
      'judgeStartedAt': 'Başlangıç',
      'judgeLastUpdate': 'Son güncelleme'
    },
  };

  static String tr(String languageCode, String key) {
    final lang = dictionary[languageCode];
    if (lang != null && lang.containsKey(key)) return lang[key]!;
    return dictionary['en']![key] ?? key;
  }
}

extension AppLocBuildContextX on BuildContext {
  String tr(String languageCode, String key) => AppLocalizations.tr(languageCode, key);
}
