import 'package:flutter/widgets.dart';

/// Add new languages by extending [supportedLanguages] and [dictionary].
class AppLocalizations {
  AppLocalizations._();

  static const List<String> supportedLanguages = ['en', 'ru', 'tr'];

  static const Map<String, Map<String, String>> dictionary = {
    'en': {
      'appTitle': 'VPS Capture',
      'setupTitle': 'VPS Capture • Settings',
      'workTitle': 'VPS Capture • Work',
      'currentThread': 'CURRENT THREAD',
      'nextThread': 'NEXT THREAD',
      'postponedParticipants': 'POSTPONED',
      'endThread': 'END',
      'clearPostponed': 'CLEAR',
      'installAutomatically': 'Install automatically',
      'pickFfmpeg': 'Pick ffmpeg path...',
      'pickFfplay': 'Pick ffplay path...',
      'startPreview': 'Start Preview',
      'stopPreview': 'Stop Preview',
      'startTestRecording': 'Start Test Recording',
      'stopTestRecording': 'Stop Test Recording',
      'notSelected': 'not selected',
      'outputFolder': 'Output folder',
      'chooseOutputFolder': 'Choose output folder',
      'captureSource': 'Capture source type',
      'scanDevices': 'Scan devices',
      'codec': 'Codec',
      'bufferMin': 'Buffer min',
      'preRollSec': 'Pre-roll sec',
      'detectedVideoDevices': 'Video devices',
      'detectedAudioDevices': 'Audio devices',
      'selectedVideoDevices': 'Choose video device',
      'selectedAudioDevices': 'Choose audio device',
      'continueToWork': 'Continue to Work Screen',
      'loadSchedule': 'Load schedule',
      'scheduleEditorLabel': 'Schedule input',
      'scheduleEditorHint': 'One line: FIO;CITY;APPARATUS (optional)',
      'applySchedule': 'Apply schedule',
      'backToSetup': 'Back to setup',
      'startHotkey': 'START (Space)',
      'stopHotkey': 'STOP (Space)',
      'postponeHotkey': 'POSTPONE (Ctr+Left Alt)',
      'startStopButtonStart': 'START',
      'startStopButtonStop': 'STOP',
      'restoreEntry': 'Restore',
      'postponeEntry': 'Postpone',
      'deleteEntry': 'Delete',
      'addParticipant': 'Add participant',
      'participantNameLabel': 'Name',
      'participantCityLabel': 'City',
      'participantApparatusLabel': 'Apparatus (optional)',
      'add': 'Add',
      'cancel': 'Cancel',
      'pending': 'PENDING',
      'active': 'ACTIVE',
      'done': 'DONE',
      'postponed': 'POSTPONED',
      'language': 'Language',
      'allThreads': 'All streams',
      'allTypes': 'All routines',
      'resetFilters': 'Reset filters',
      'displayedCounter': 'Displayed ',
      'nameGifsTitre': 'GIF-titles',
      'labelTimerGifs': 'Timer GIFs (sec)',
      'hintTimerGifs': 'Enter a number',
      'suffixTimerGifs': 'sec',
      'setupVersion': 'version',
      'fullResetSettings': 'Full reset settings',
      'fullResetWarningTitle': 'Reset all settings?',
      'fullResetWarningMessage': 'This will return all settings to defaults, clear the schedule queue and delete saved temporary data. This action cannot be undone.',
      'reset': 'Reset',
      'ffmpegErrorTitle': 'Recording could not start',
      'ffmpegErrorMessage': 'ffmpeg reported an error when recording started. You can copy or save the full report for the developer.',
      'copyError': 'Copy report',
      'saveError': 'Save report',
      'close': 'Close',
      'ffmpegErrorCopied': 'ffmpeg error report copied to clipboard',
      'ffmpegErrorSaved': 'ffmpeg error report saved',
      "pasteFromClipboard": "Paste from the buffer",
      "loadFromFile": "Upload from a file",
      "pasteScheduleData": "Insert the start list",
      "scheduleData": "The starting list",
      "pasteScheduleHint": "Insert the start list here...",
      "clipboardEmpty": "The clipboard is empty",
      "emptyScheduleData": "The start list is empty",
      "load": "Load",
      "labelDropDownThread": "Thread",
      "labelDropDownRoutines": "Routin",
      "labelDropDownTitres": "Titer",
      "labelDropDownThreadList": "THREAD"
    },
    'ru': {
      'appTitle': 'ВПС Захват',
      'setupTitle': 'ВПС Захват • Настройки',
      'workTitle': 'ВПС Захват • Работа',
      'currentThread': 'ТЕКУЩИЙ ПОТОК',
      'nextThread': 'СЛЕДУЮЩИЙ ПОТОК',
      'postponedParticipants': 'ОТЛОЖЕННЫЕ',
      'endThread': 'КОНЕЦ',
      'clearPostponed': 'ОЧИСТИТЬ',
      'installAutomatically': 'Установить автоматически',
      'pickFfmpeg': 'Выбрать путь к ffmpeg...',
      'pickFfplay': 'Выбрать путь к ffplay...',
      'startPreview': 'Запустить превью',
      'stopPreview': 'Остановить превью',
      'startTestRecording': 'Запустить тестовую запись',
      'stopTestRecording': 'Остановить тестовую запись',
      'notSelected': 'не выбрано',
      'outputFolder': 'Папка вывода',
      'chooseOutputFolder': 'Выбрать папку вывода',
      'captureSource': 'Тип источника захвата',
      'scanDevices': 'Сканировать устройства',
      'codec': 'Кодек',
      'bufferMin': 'Буфер, мин',
      'preRollSec': 'Преролл, сек',
      'detectedVideoDevices': 'Видеоустройства',
      'detectedAudioDevices': 'Аудиоустройства',
      'selectedVideoDevices': 'Выберите видеоустройство',
      'selectedAudioDevices': 'Выберите аудиоустройство',
      'continueToWork': 'Перейти к рабочему экрану',
      'loadSchedule': 'Загрузить расписание',
      'scheduleEditorLabel': 'Ввод расписания',
      'scheduleEditorHint': 'Одна строка: ФИО;ГОРОД;СНАРЯД (необязательно)',
      'applySchedule': 'Применить расписание',
      'backToSetup': 'Назад к настройке',
      'startHotkey': 'СТАРТ (Пробел)',
      'stopHotkey': 'СТОП (Пробел)',
      'postponeHotkey': 'ОТЛОЖИТЬ (Ctr+Левый Alt)',
      'startStopButtonStart': 'СТАРТ',
      'startStopButtonStop': 'СТОП',
      'restoreEntry': 'Вернуть',
      'postponeEntry': 'Отложить',
      'deleteEntry': 'Удалить',
      'addParticipant': 'Добавить участницу',
      'participantNameLabel': 'ФИО',
      'participantCityLabel': 'Город',
      'participantApparatusLabel': 'Снаряд (необязательно)',
      'add': 'Добавить',
      'cancel': 'Отмена',
      'pending': 'В ОЧЕРЕДИ',
      'active': 'АКТИВНО',
      'done': 'ГОТОВО',
      'postponed': 'ОТЛОЖЕНО',
      'language': 'Язык',
      'allThreads': 'Все потоки',
      'allTypes': 'Все виды',
      'resetFilters': 'Сбросить фильтры',
      'displayedCounter': 'Отображено ',
      'nameGifsTitre': 'GIF-титры',
      'labelTimerGifs': 'GIF-таймер (сек)',
      'hintTimerGifs': 'Введите число',
      'suffixTimerGifs': 'сек',
      'setupVersion': 'версия',
      'fullResetSettings': 'Полный сброс настроек',
      'fullResetWarningTitle': 'Сбросить все настройки?',
      'fullResetWarningMessage': 'Все настройки вернутся к значениям по умолчанию, очередь расписания и временные данные будут удалены. Это действие нельзя отменить.',
      'reset': 'Сбросить',
      'ffmpegErrorTitle': 'Не удалось начать запись',
      'ffmpegErrorMessage': 'Во время старта записи ffmpeg вернул ошибку. Полный отчет можно скопировать или сохранить и отправить разработчику.',
      'copyError': 'Скопировать отчет',
      'saveError': 'Сохранить отчет',
      'close': 'Закрыть',
      'ffmpegErrorCopied': 'Отчет об ошибке ffmpeg скопирован',
      'ffmpegErrorSaved': 'Отчет об ошибке ffmpeg сохранен',
      "pasteFromClipboard": "Вставить из буфера",
      "loadFromFile": "Загрузить из файла",
      "pasteScheduleData": "Вставить стартовый список",
      "scheduleData": "Стартовый список",
      "pasteScheduleHint": "Вставьте сюда стартовый список...",
      "clipboardEmpty": "Буфер обмена пуст",
      "emptyScheduleData": "Стартовый список пуст",
      "load": "Загрузить",
      "labelDropDownThread": "Поток",
      "labelDropDownRoutines": "Вид",
      "labelDropDownTitres": "Титр",
      "labelDropDownThreadList": "ПОТОК"
    },
    'tr': {
      'appTitle': 'VPS Capture',
      'setupTitle': 'VPS Capture • Ayarlar',
      'workTitle': 'VPS Capture • Çalışma',
      'currentThread': 'MEVCUT AKIŞ',
      'nextThread': 'SONRAKİ AKIŞ',
      'postponedParticipants': 'ertelenmiş',
      'endThread': 'BİTİŞ',
      'clearPostponed': 'açık',
      'installAutomatically': 'Otomatik kur',
      'pickFfmpeg': 'ffmpeg yolunu seç...',
      'pickFfplay': 'ffplay yolunu seç...',
      'startPreview': 'Önizlemeyi başlat',
      'stopPreview': 'Önizlemeyi durdur',
      'startTestRecording': 'Test kaydını çalıştır',
      'stopTestRecording': 'Test kaydını durdur',
      'notSelected': 'seçilmedi',
      'outputFolder': 'Çıktı klasörü',
      'chooseOutputFolder': 'Çıktı klasörü seç',
      'captureSource': 'Yakalama kaynağı türü',
      'scanDevices': 'Cihazları tara',
      'codec': 'Kodek',
      'bufferMin': 'Arabellek dk',
      'preRollSec': 'Ön kayıt sn',
      'detectedVideoDevices': 'Video cihazları',
      'detectedAudioDevices': 'Ses cihazları',
      'selectedVideoDevices': 'Bir video cihazı seçin',
      'selectedAudioDevices': 'Bir ses cihazı seçin',
      'continueToWork': 'Çalışma ekranına geç',
      'loadSchedule': 'Program yükle',
      'scheduleEditorLabel': 'Program girişi',
      'scheduleEditorHint': 'Her satır: AD SOYAD;ŞEHİR;EKİPMAN (opsiyonel)',
      'applySchedule': 'Programı uygula',
      'backToSetup': 'Kuruluma dön',
      'startHotkey': 'BAŞLAT (Space)',
      'stopHotkey': 'DURDUR (Space)',
      'postponeHotkey': 'ERTELE (Ctr+Sol Alt)',
      'startStopButtonStart': 'BAŞLAT',
      'startStopButtonStop': 'DURDUR',
      'restoreEntry': 'Geri yükle',
      'postponeEntry': 'Ertele',
      'deleteEntry': 'Sil',
      'addParticipant': 'Katılımcı ekle',
      'participantNameLabel': 'Ad Soyad',
      'participantCityLabel': 'Şehir',
      'participantApparatusLabel': 'Ekipman (opsiyonel)',
      'add': 'Ekle',
      'cancel': 'İptal',
      'pending': 'BEKLİYOR',
      'active': 'AKTİF',
      'done': 'TAMAM',
      'postponed': 'ERTELENDİ',
      'language': 'Dil',
      'allThreads': 'Tüm konular',
      'allTypes': 'Her türlü',
      'resetFilters': 'Filtreleri sıfırla',
      'displayedCounter': 'Görüntülenen ',
      'nameGifsTitre': 'GIF Kredileri',
      'labelTimerGifs': 'GIF zamanlayıcısı (sn)',
      'hintTimerGifs': 'Numarayı girin',
      'suffixTimerGifs': 'sn',
      'setupVersion': 'versiyon',
      'fullResetSettings': 'Ayarları tamamen sıfırla',
      'fullResetWarningTitle': 'Tüm ayarlar sıfırlansın mı?',
      'fullResetWarningMessage': 'Bu işlem tüm ayarları varsayılana döndürür, program kuyruğunu temizler ve geçici verileri siler. Bu işlem geri alınamaz.',
      'reset': 'Sıfırla',
      'ffmpegErrorTitle': 'Kayıt başlatılamadı',
      'ffmpegErrorMessage': 'Kayıt başlatılırken ffmpeg hata bildirdi. Geliştiriciye göndermek için tam raporu kopyalayabilir veya kaydedebilirsiniz.',
      'copyError': 'Raporu kopyala',
      'saveError': 'Raporu kaydet',
      'close': 'Kapat',
      'ffmpegErrorCopied': 'ffmpeg hata raporu panoya kopyalandı',
      'ffmpegErrorSaved': 'ffmpeg hata raporu kaydedildi',
      "pasteFromClipboard": "Arabellekten yapıştır",
      "loadFromFile": "Bir dosyadan yükleme",
      "pasteScheduleData": "Başlangıç listesini ekle",
      "scheduleData": "Başlangıç listesi",
      "pasteScheduleHint": "Başlangıç listesini buraya ekleyin...",
      "clipboardEmpty": "Pano boş",
      "emptyScheduleData": "Başlangıç listesi boş",
      "load": "Yüklemek",
      "labelDropDownThread": "Konu",
      "labelDropDownRoutines": "Rutin",
      "labelDropDownTitres": "Titre",
      "labelDropDownThreadList": "KONU"
    },
  };

  static String tr(String languageCode, String key) {
    final lang = dictionary[languageCode];
    if (lang != null && lang.containsKey(key)) return lang[key]!;
    return dictionary['en']![key] ?? key;
  }
}

extension AppLocBuildContextX on BuildContext {
  String tr(String languageCode, String key) => AppLocalizations.tr(languageCode, key);
}
